### ISSUE TITLE
Excuse me: Where can I download the ADLINk PCI-9114 DLL file and whether it contains a C++demo？

### ISSUE THREAD

**Issue by wanghuqiang123** [ADLINK/sema-windows#1]
请问：哪里可以下载ADLINk PCI-9114 DLL文件，是否有C++ demo？

Our company has purchased ADLINK PCI-9114 data acquisition card, and we are planning to develop it in C++, but we do not know how to use it

Thank you very much. We really need these urgently

**Comment by kennethtjlin** [comment]
你好, 你可以在adlink 的官網下載的 driver中下載  PCIS-DASK, 裡面有包含你開發所需要的東西,包含 DLL, samples...
https://www.adlinktech.com.cn/Products/Data_Acquisition/Multi-FunctionDAQ/PCI-9114_Series?lang=zh-cn

Hi, pelase download the driver named PCIS-DASK from adlink website, waht you need including dll, samples are on it.
https://www.adlinktech.com/Products/Data_Acquisition/Multi-FunctionDAQ/PCI-9114_Series?lang=en
